const productRoute = require('./product')
const campusRoute = require('./campus')
const customerRoute = require('./customer')
const ownerRoute = require('./owner')
const shopRoute = require('./shop')
const categoryRoute = require('./category')
const employeeRoute = require('./employee')
const invoiceRoute = require('./invoice')
const invoiceItemRoute = require('./invoiceItem')
const userRoute = require('./user')
const authRoute = require('./auth')
const routes = (app) => {
  app.use('/api/products', productRoute)
  app.use('/api/campus', campusRoute)
  app.use('/api/customers', customerRoute)
  app.use('/api/owner', ownerRoute)
  app.use('/api/shop', shopRoute)
  app.use('/api/category', categoryRoute)
  app.use('/api/employee', employeeRoute)
  app.use('/api/invoices', invoiceRoute)
  app.use('/api/invoiceItems', invoiceItemRoute)
  app.use('/api/users', userRoute)
  app.use('/api/auth', authRoute)
}

module.exports = routes
